# Jupyter notebook基礎


## 実行環境
### Anaconda 　Python関係の環境が揃う
Jupyter notebook ; Pythonの<font color=red>プログラム部分</font>と<font color=red>ドキュメント部</font>（プログラムではない:Marldown言語で記述）が一緒になってプログラム部を順番に動作できる  
（Spyder : PythonプログラムをC-Padのように利用できる）
## Jupyter notebookの使い方
<font color=red>Cell</font>とはJupyter notebookでの１つの塊部分  
+アイコン　Cellの新規追加  
✂アイコン　Cellの削除  
CodeとMarkdownの選択　プルグラム部（Code）にするかドキュメント（Markdown）にするかの選択（Markdown言語で入力後に「Shift+enter」でドキュメントになる）  
▶Runで現在のCellのプログラム実行


セルを選択した状態で  
セルの左側が青色の時は<font color=red>command mode</font>となっており，command modeの機能が使えます．  
機能には，新しいセルを上に挿入（a）や新しいセルを下に挿入（b）や現在のセルを削除（X）,セルをMarkdownに変更(m），セルをCodeに変更（Y）などがあります．

セル（Markdown）に文字列を入力した後に[Shift]+[Enter]を押すとドキュメントに変わります．（文字列にはHTMLのタグも使えます．例えば文字列を赤色にしたい場合は，＜font color=red>文字列</font＞(全て半角文字）で囲みます．）

セル（Code）にプログラムを入力した後[Ctrl]+[Enter]でそのセルのプログラムを実行します．

#### 練習問題

この行の下に新しいセルをつくり，Markdown言語で「これからJupyter Notebookの勉強を始めます．」というドキュメントを生成せよ．（ただし，Jupyter Notebookの部分は赤色とする）

これから<font color="red">Jupyter Notebook</font>の勉強を始めます

## 行列

Numpyを使うと行列計算もできます。
まずは、行列の作成方法から説明します。次の例は、0〜8までの数字を3×3行列で表現するものです。`arange`関数は指定した連続した整数を発生する機能を持ちます。`arange(9)`とした場合、0から8までの整数を発生します。それを`reshape`関数で3×3の行列に分割しています。
これで変数`array1`に3×3の行列が作られます。

In [3]:
import numpy as np
a=np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [4]:
import numpy as np
array1 = np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


行列から、行や列のみを抜き出したいときは、「[行範囲:列範囲]」のように表記します。それぞれの範囲は、「開始インデックス,終了インデックス」のように、カンマで区切って指定します。開始インデックスや終了インデックスを省略したときは、それぞれ「最初から」「末尾まで」という意味になります。
たとえば、次のように「`[0,:]`」を指定すると、「行は1行目」「列はすべて」という意味になるので、1行目のすべての列を取り出すことができます。なお、インデックスは0からはじまりますが、対象の行列は1からはじまるので注意しましょう。

In [5]:
# 1行目のみ取り出し
a=array1[0,:]
print(a)

[0 1 2]


In [6]:
# ２行目と３行目を取り出し，（最初の行範囲は０という数値から，[1,2]というリストに変更されている）
a=array1[[1,2],:]
print(a)

[[3 4 5]
 [6 7 8]]


1列目のすべての行を取り出すには、「`[:,0]`」を指定します。これは「列は1列目」「行はすべて」という意味です。

In [7]:
# 1列目のみ取り出し
a=array1[:,0]
print(a)

[0 3 6]


#### 練習問題

４行×４列の行列をndarray（numpy配列）として作成し，２列目と３列目のみとりだした４行×２列の行列をつくり表示するプログラムを作成しなさい．

In [8]:
## 4 x 4
array2 = np.arange(16).reshape(4, 4)
print(array2)

array3 = array2[:, [1, 2]]
print(array3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


#### 行列の演算

行列の掛け算をしてみましょう。この計算方法がわからない方は、線形代数の復習をしてください。

まずは、掛け算する対象とする行列を作成しましょう。次の例では、3×3の行列を作成し、変数`array2`に代入しています。

In [9]:
import numpy as np
array2 = np.arange(9,18).reshape(3,3)
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


この行列と、先の`array1`の行列を掛け算してみましょう。
行列の掛け算では、`dot`関数を使います。おなじ計算は'@'でも計算できます。間違えて`*`を使うと、行列の掛け算ではなく、それぞれの要素を掛け算してしまうので、注意しましょう。

In [10]:
# 行列の積
a=np.dot(array1, array2)
print(a)

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


In [11]:
a=array1 @ array2
print(a)

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


In [12]:
# 要素どうしの積（＊記号では要素同士と積となるので注意が必要です．）
a=array1 * array2
print(a)

[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


#### 要素が0や1の行列を作る

データ分析では、要素が0や1の行列を作りたいことがあります。その場合、「`[0, 0, 0, 0, 0…]`」のようにひとつずつ要素を記述する（もしくは`for`文を使って繰り返し処理で作る）のは大変なので、専用の構文が用意されています。
次のように「`np.zeros`」を指定すると、すべての要素が0の行列を作れます。同様に「`np.ones`」は、すべての要素が1の行列を作ります。`dtype`オプションでは、データの型を指定します。`int64`は64ビット整数、`float64`は64ビット浮動小数です。次のコードは、要素がすべて0（`int64`）の2行3列の行列、要素がすべて1（`float64`）の2行3列の行列を、それぞれ作成する例です。

In [14]:
import numpy as np
print(np.zeros((2, 3), dtype = np.int64))
print(np.ones((2, 3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


またリストへの乗算を行うことでも作成できます．

In [15]:
import numpy as np
a=3*4
print(a)
b=[3]*4
print(b)

12
[3, 3, 3, 3]


リストはnumpy配列（ndarray）に変換してから行列にすることもできます．（ndarrayでないとreshape関数がないためエラーとなる）（最初の例では変換していないためエラーとなりますが，後の例ではエラーとなりません．）

In [16]:
c=b.reshape(2,2)
print(c)

AttributeError: 'list' object has no attribute 'reshape'

In [17]:
ndarray_b=np.array(b)
c=ndarray_b.reshape(2,2)
print(c)

[[3 3]
 [3 3]]


２つの行列を'＊'記号で乗算すると，要素同士の積となります．

In [18]:
d=c*c
print(d)

[[9 9]
 [9 9]]


掛ける数がすべて同じであれば，数値*行列でも同じことができます．

In [19]:
d=3*c
print(d)

[[9 9]
 [9 9]]


#### 練習問題
要素がすべて1の5行5列の行列を作成し、その行列×行列をする計算をしてみましょう。

In [22]:
# 5行5列
array1 = np.arange(25).reshape(5,5)
array2 = np.arange(25).reshape(5,5)

# 行列の積
ans=np.dot(array1, array2)
print(ans)

[[ 150  160  170  180  190]
 [ 400  435  470  505  540]
 [ 650  710  770  830  890]
 [ 900  985 1070 1155 1240]
 [1150 1260 1370 1480 1590]]


#### 練習問題

1～9の数値をもつ３×３行列Aと，11～19の数値を持つ３×３行列Bを作成し，AとBの積を２種類（行列積と要素ごとの積）を計算し表示するプログラムを作成せよ．

In [25]:
arrayA = np.arange(1, 10).reshape(3, 3)
arrayB = np.arange(11, 20).reshape(3, 3)

# print matrixes
print(arrayA)
print(arrayB)

print("---------------------------------")

# 行列の積
ans = np.dot(arrayA, arrayB)
print(ans)

# 要素ごとの積
ans = arrayA * arrayB
print(ans)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
---------------------------------
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


## 行列積と内積

行列を１行ｍ列とｍ行１列で行列積を求めると，２つのベクトル（行列）の内積を計算したことになります．

In [ ]:
import numpy as np
m1=np.arange(0,2) #このではreshapeかけていないので１次元となる
print('m1')
print(m1)
m2=np.arange(0,2).reshape(2,1)
print('m2')
print(m2)
a=m1 @ m2
print('m1 @ m2')
print(a)
b=int(a)
print('int(a)')
print(b)

## 2つのベクトル（行列）の行列積による内積（※転置していないので注意）

In [ ]:
import numpy as np
m1=np.arange(1,4)
print('m1')
print(m1)
m2=np.arange(2,5)
print('m2')
print(m2)
a=m1 @ m2
print('m1 @ m2')
print(a)


In [ ]:
import numpy as np
m1=np.arange(1,21)
print('m1')
print(m1)
m2=np.arange(1,21)
print('m2')
print(m2)
a=m1 @ m2
print('m1 @ m2')
print(a)


#### 練習問題

１～１０までの数値の２乗の合計を計算して表示するプログラムを作成せよ．ただし，１から１０の値を持つリストを２つ作り，そのリスト内積から合計を求めて表示すること．

In [ ]:
import numpy as np
a = np.arange(1, 11)
print(a)
print(a @ a)

## 逆行列

行列は逆行列も計算できます。  

In [ ]:
import numpy as np
a1=np.arange(1,5).reshape(2,2)
a2=np.linalg.inv(a1)
print(a2)


#### 練習問題
次の行列の逆行列を求めましょう。

[[2 3]  
 [4 5]]


In [26]:
arr = np.array([[2, 3], [4, 5]])
print(arr)
print(np.linalg.inv(arr))

[[2 3]
 [4 5]]
[[-2.5  1.5]
 [ 2.  -1. ]]


## 演習課題1
２つのベクトル（1,2,3)と(4,5,6)の内積を計算する関数を作成せよ。関数には２つの引数があり、それぞれがベクトルを表す。
戻り値は内積値（1つのスカラー値）であり、これを関数を呼び出したプログラムで（表示するのは関数の中ではない）表示する。

In [1]:
import numpy as np

def dot_product(a,b):
    return a @ b

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(dot_product(a, b))


32


## 演習課題２
２つの行列を引数として与え（１つ目をm×n行列，２つ目をn×k行列とする），その行列積(m×k行列)を計算して表示するプログラムを作成せよ。  
与える引数は１つ目を下記a，２つ目を下記bとする．  
行列a  
[[1 2 3]  
 [4 5 6]]  
行列b  
[[1 2]  
 [3 4]  
 [5 6]]  
 

In [3]:
import numpy as np

matrixA = np.arange(1,7).reshape(2,3)
matrixB = np.arange(1,7).reshape(3,2)

ans = np.dot(matrixA, matrixB)
print(ans)


[[22 28]
 [49 64]]


## 演習課題３
３つの行列の行列積（ｍ×ｎ，ｎ×o，o×ｐの積（左から掛ける）をｍ×ｐ行列とする）を求めて表示するプログラムを作成せよ．

In [6]:
import numpy as np

matrix_elements = [3, 4, 5, 6]

matrixs = [
    np.arange(matrix_elements[i] * matrix_elements[i + 1]).reshape(
        matrix_elements[i], matrix_elements[i + 1]
    )
    for i in range(len(matrix_elements) - 1)
]

ans = matrixs[0] @ matrixs[1] @ matrixs[2]

print(ans)

[[ 5280  5690  6100  6510  6920  7330]
 [15360 16530 17700 18870 20040 21210]
 [25440 27370 29300 31230 33160 35090]]
